export const IPC_METHODS = [
  {
    namespace: "dashboard",
    method: "getHomeDashboard",
    providerMethod: "getHomeDashboard",
    channel: "dashboard:getHomeDashboard",
  },
  {
    namespace: "agentChat",
    method: "getAgentChat",
    providerMethod: "getAgentChat",
    channel: "agentChat:getAgentChat",
  },
  {
    namespace: "agentChat",
    method: "prepareMessageDraft",
    providerMethod: "prepareAgentChatMessageDraft",
    channel: "agentChat:message:prepareDraft",
  },
  {
    namespace: "agentChat",
    method: "previewContextPack",
    providerMethod: "previewAgentChatContextPack",
    channel: "agentChat:context:preview",
  },
  {
    namespace: "agentChat",
    method: "previewToolPlan",
    providerMethod: "previewAgentChatToolPlan",
    channel: "agentChat:toolPlan:preview",
  },
  {
    namespace: "agentChat",
    method: "runDryMessage",
    providerMethod: "runAgentChatDryMessage",
    channel: "agentChat:message:runDry",
  },
  {
    namespace: "agentChat",
    method: "resetSession",
    providerMethod: "resetAgentChatSession",
    channel: "agentChat:session:reset",
  },
  {
    namespace: "agentChat",
    method: "restoreSession",
    providerMethod: "restoreAgentChatSession",
    channel: "agentChat:session:restore",
  },
  {
    namespace: "agentChat",
    method: "sendMessage",
    providerMethod: "sendAgentChatMessage",
    channel: "agentChat:message:send",
  },
  {
    namespace: "agentChat",
    method: "streamMessage",
    providerMethod: "streamAgentChatMessage",
    channel: "agentChat:message:stream",
    eventChannel: "agentChat:message:stream:event",
  },
  {
    namespace: "agentChat",
    method: "cancelStream",
    providerMethod: "cancelAgentChatStream",
    channel: "agentChat:message:stream:cancel",
  },
  {
    namespace: "agentChat",
    method: "attachKnowledgeContext",
    providerMethod: "attachKnowledgeContextToAgentChat",
    channel: "agentChat:knowledgeContext:attach",
  },
  {
    namespace: "agentChat",
    method: "listKnowledgeContexts",
    providerMethod: "listAgentChatKnowledgeContexts",
    channel: "agentChat:knowledgeContext:list",
  },
  {
    namespace: "agentChat",
    method: "removeKnowledgeContext",
    providerMethod: "removeKnowledgeContextFromAgentChat",
    channel: "agentChat:knowledgeContext:remove",
  },
  {
    namespace: "agentChat",
    method: "clearKnowledgeContexts",
    providerMethod: "clearAgentChatKnowledgeContexts",
    channel: "agentChat:knowledgeContext:clear",
  },
  {
    namespace: "knowledge",
    method: "getKnowledgeBase",
    providerMethod: "getKnowledgeBase",
    channel: "knowledge:getKnowledgeBase",
  },
  {
    namespace: "kb",
    method: "getDocumentImage",
    providerMethod: "getKnowledgeDocumentImage",
    channel: "kb:getDocumentImage",
  },
  {
    namespace: "agentManagement",
    method: "getAgentManagement",
    providerMethod: "getAgentManagement",
    channel: "agentManagement:getAgentManagement",
  },
  {
    namespace: "repository",
    method: "getCodeRepository",
    providerMethod: "getCodeRepository",
    channel: "repository:getCodeRepository",
  },
  {
    namespace: "music",
    method: "getLocalMusic",
    providerMethod: "getLocalMusic",
    channel: "music:getLocalMusic",
  },
  {
    namespace: "intel",
    method: "getIntelCenter",
    providerMethod: "getIntelCenter",
    channel: "intel:getIntelCenter",
  },
  {
    namespace: "settings",
    method: "getSettings",
    providerMethod: "getSettings",
    channel: "settings:getSettings",
  },
  {
    namespace: "settings",
    method: "selectLocalSourcePath",
    providerMethod: "selectLocalSourcePath",
    channel: "settings:selectLocalSourcePath",
  },
  {
    namespace: "settings",
    method: "saveLocalSourcePath",
    providerMethod: "saveLocalSourcePath",
    channel: "settings:saveLocalSourcePath",
  },
  {
    namespace: "widgets",
    method: "getWidgets",
    providerMethod: "getWidgets",
    channel: "widgets:getWidgets",
  },
  {
    namespace: "system",
    method: "getAppStatus",
    providerMethod: "getAppStatus",
    channel: "system:app:status",
  },
  {
    namespace: "system",
    method: "getSettingsSummary",
    providerMethod: "getSettingsSummary",
    channel: "system:settings:summary",
  },
  {
    namespace: "system",
    method: "listTasks",
    providerMethod: "listTasks",
    channel: "system:task:list",
  },
  {
    namespace: "kb",
    method: "listSources",
    providerMethod: "listKnowledgeSources",
    channel: "kb:source:list",
  },
  {
    namespace: "kb",
    method: "listDocuments",
    providerMethod: "listKnowledgeDocuments",
    channel: "kb:document:list",
  },
  {
    namespace: "kb",
    method: "listTree",
    providerMethod: "listKnowledgeFileTree",
    channel: "kb:fileTree:list",
  },
  {
    namespace: "kb",
    method: "getIndexStatus",
    providerMethod: "getKnowledgeIndexStatus",
    channel: "kb:index:status",
  },
  {
    namespace: "kb",
    method: "searchLocal",
    providerMethod: "searchKnowledgeLocal",
    channel: "kb:search:local",
  },
  {
    namespace: "kb",
    method: "getDocumentPreview",
    providerMethod: "getKnowledgeDocumentPreview",
    channel: "kb:document:preview",
  },
  {
    namespace: "kb",
    method: "startIndex",
    providerMethod: "startKnowledgeIndex",
    channel: "kb:index:start",
  },
  {
    namespace: "codeRepo",
    method: "listRepositories",
    providerMethod: "listCodeRepositories",
    channel: "codeRepo:repository:list",
  },
  {
    namespace: "codeRepo",
    method: "getGitSummary",
    providerMethod: "getCodeGitSummary",
    channel: "codeRepo:git:summary",
  },
  {
    namespace: "codeRepo",
    method: "listFiles",
    providerMethod: "listCodeRepositoryFiles",
    channel: "codeRepo:file:list",
  },
  {
    namespace: "codeRepo",
    method: "getMetrics",
    providerMethod: "getCodeRepositoryMetrics",
    channel: "codeRepo:metrics:get",
  },
  {
    namespace: "codeRepo",
    method: "getStructure",
    providerMethod: "getCodeRepositoryStructure",
    channel: "codeRepo:structure:get",
  },
  {
    namespace: "codeRepo",
    method: "scanRepository",
    providerMethod: "scanCodeRepository",
    channel: "codeRepo:repository:scan",
    permission: "denied",
    message: "Repository scanning is disabled in phase 1.",
  },
  {
    namespace: "agent",
    method: "listAgents",
    providerMethod: "listAgents",
    channel: "agent:agent:list",
  },
  {
    namespace: "agent",
    method: "listSessions",
    providerMethod: "listAgentSessions",
    channel: "agent:session:list",
  },
  {
    namespace: "agent",
    method: "sendMessage",
    providerMethod: "sendAgentMessage",
    channel: "agent:session:sendMessage",
    permission: "notImplemented",
    message: "Agent message execution is not implemented in phase 1.",
  },
  {
    namespace: "llm",
    method: "listProviders",
    providerMethod: "listLlmProviders",
    channel: "llm:provider:list",
  },
  {
    namespace: "llm",
    method: "listModels",
    providerMethod: "listLlmModels",
    channel: "llm:model:list",
  },
  {
    namespace: "llm",
    method: "getProviderStatus",
    providerMethod: "getLlmProviderStatus",
    channel: "llm:provider:status",
  },
  {
    namespace: "llm",
    method: "validateProviderConfig",
    providerMethod: "validateLlmProviderConfig",
    channel: "llm:provider:validate",
  },
  {
    namespace: "llm",
    method: "sendMessage",
    providerMethod: "sendLlmMessage",
    channel: "llm:message:send",
    permission: "notImplemented",
    message: "LLM message execution is not implemented in phase 7.",
  },
  {
    namespace: "llm",
    method: "sendTextMessage",
    providerMethod: "sendLlmTextMessage",
    channel: "llm:message:sendText",
  },
  {
    namespace: "permission",
    method: "listRequests",
    providerMethod: "listPermissionRequests",
    channel: "permission:request:list",
  },
  {
    namespace: "permission",
    method: "evaluateToolRequest",
    providerMethod: "evaluateToolRequest",
    channel: "permission:tool:evaluate",
  },
  {
    namespace: "permission",
    method: "decideRequest",
    providerMethod: "decidePermissionRequest",
    channel: "permission:request:decide",
    permission: "notImplemented",
    message: "Permission decisions are not implemented in phase 7.",
  },
  {
    namespace: "tool",
    method: "dryRun",
    providerMethod: "dryRunTool",
    channel: "tool:dryRun",
  },
  {
    namespace: "tool",
    method: "execute",
    providerMethod: "executeTool",
    channel: "tool:execute",
    permission: "denied",
    message: "Tool execution is disabled in phase 7.",
  },
  {
    namespace: "intel",
    method: "getServiceStatus",
    providerMethod: "getIntelServiceStatus",
    channel: "intel:service:status",
  },
  {
    namespace: "intel",
    method: "getDashboardSummary",
    providerMethod: "getIntelDashboardSummary",
    channel: "intel:dashboard:summary",
  },
  {
    namespace: "intel",
    method: "getSourceHealth",
    providerMethod: "getIntelSourceHealth",
    channel: "intel:source:health",
  },
  {
    namespace: "intel",
    method: "listReports",
    providerMethod: "listIntelReports",
    channel: "intel:report:list",
  },
  {
    namespace: "intel",
    method: "listLogs",
    providerMethod: "listIntelLogs",
    channel: "intel:log:list",
  },
  {
    namespace: "intel",
    method: "startService",
    providerMethod: "startIntelService",
    channel: "intel:service:start",
    permission: "denied",
    message: "Starting local-intel is a Level 3 operation and is disabled in phase 1.",
  },
  {
    namespace: "intel",
    method: "stopService",
    providerMethod: "stopIntelService",
    channel: "intel:service:stop",
    permission: "denied",
    message: "Stopping local-intel is a Level 3 operation and is disabled in phase 1.",
  },
  {
    namespace: "intel",
    method: "runUpdateNow",
    providerMethod: "runIntelUpdateNow",
    channel: "intel:update:runNow",
    permission: "denied",
    message: "Running local-intel updates is a Level 3 operation and is disabled in phase 1.",
  },
  {
    namespace: "music",
    method: "getPlaybackState",
    providerMethod: "getMusicPlaybackState",
    channel: "music:playback:state",
  },
  {
    namespace: "music",
    method: "play",
    providerMethod: "playMusicTrack",
    channel: "music:playback:play",
    permission: "denied",
    message: "Playback control is disabled in phase 1.",
  },
  {
    namespace: "voice",
    method: "getVoiceStatus",
    providerMethod: "getVoiceStatus",
    channel: "voice:status:get",
    permission: "notImplemented",
    message: "Voice status is not implemented in phase 1.",
  },
  {
    namespace: "voice",
    method: "startDictation",
    providerMethod: "startDictation",
    channel: "voice:dictation:start",
    permission: "notImplemented",
    message: "Voice dictation is not implemented in phase 1.",
  },
];

export const IPC_CHANNELS = IPC_METHODS.reduce((channels, item) => {
  return {
    ...channels,
    [item.namespace]: {
      ...(channels[item.namespace] ?? {}),
      [item.method]: item.channel,
    },
  };
}, {});

export const IPC_WINDOW_CHANNELS = {
  close: "window:close",
  maximize: "window:maximize",
  minimize: "window:minimize",
};

export const IPC_STREAM_CHANNELS = {
  agentChat: {
    message: "agentChat:message:stream:event",
  },
};
